version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      next-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
          - "eslint-config-next"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - "next*"
          - "react*"
          - "prisma*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
