name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  lint-typecheck-build:
    runs-on: ubuntu-latest
    name: Lint, Typecheck & Build
    env:
      DATABASE_URL: "postgresql://user:password@localhost:5432/mydb"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run linter
        run: npm run lint

      - name: Build
        run: npm run build
